### ISSUE TITLE
How to change PVP button template

### ISSUE THREAD

**Issue by Blackhatfrance** [AxelBjork/Rush-Royale-Bot#1]
Hi,
Thank you for you work, I've always tried to learn about python and IA gaming bot.
I've successful using your script with my Mac M1

I have issues with my main account, the PVP icon is not the same, I tried to remplace the PVP icon but I've broken everything (error, icon is not is template blablabla)

![image](https://user-images.githubusercontent.com/78060667/171781586-a0beec84-5fe3-4678-b009-78116030d096.png)

Do you have an idea how to change the template or reseting ?

Thank you

**Comment by Blackhatfrance** [comment]
![image](https://user-images.githubusercontent.com/78060667/171789659-e236968c-74a3-4514-ae38-6fa0999d721c.png)

**Comment by AxelBjork** [comment]
Hello,

Thanks for the report, obviously this is still work in progress but
