### ISSUE TITLE
Always Quiting

### ISSUE THREAD

**Issue by rodrigoranieri** [AxelBjork/Rush-Royale-Bot#12]
hello AxelBjork, first, thanks for your wonderful work.

Im trying to run the bot and got this error. 

G:\Games\bot\Rush-Royale-Bot-main>jupyter notebook
[I 13:32:49.893 NotebookApp] Serving notebooks from local directory: G:\Games\bot\Rush-Royale-Bot-main
[I 13:32:49.893 NotebookApp] Jupyter Notebook 6.4.12 is running at:
[I 13:32:49.893 NotebookApp] http://localhost:8888/?token=7f75f856010b71022d2e4187762900667af8a93bb14f2897
[I 13:32:49.894 NotebookApp]  or http://127.0.0.1:8888/?token=7f75f856010b71022d2e4187762900667af8a93bb14f2897
[I 13:32:49.894 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:32:49.943 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/xxx/AppData/jupyter/runtime/nbserver-24488-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=7f75f856010b71022d2e4187762900667af8a93bb14f2897
     or http://127.0.0.1:8888/?token=7f75f856010b71022d2e4187762900667af8a93bb14f2897
[I 13:33:07.158 NotebookApp] Kernel started: 9da57ad9-e136-4964-afe4-260e60edbf9d, name: python3
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 4aa2e676-ae2a-42b2-b5ae-f67b94b00ed2
List of devices attached
emulator-5554   device

error: no such device '\r:5555'
error: no such device '':5555'
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
G:\Games\bot\sc\scrcpy-server: 1 file pushed, 0 skipped. 44.2 MB/s (41159 bytes in 0.001s)
[server] INFO: Device: OnePlus ONEPLUS A3010 (Android 7.1.1)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920
/system/bin/sh: G:Gamesbotscadb: not found
Events injected: 1
## Network stats: elapsed time=6ms (0ms mobile, 0ms wifi, 6ms not connected)
/sdcard/bot_feed.png: 1 file pulled, 0 skipped. 34.8 MB/s (1490995 bytes in 0.041s)
[I 13:34:01.697 NotebookApp] Saving file at /RR_bot.ipynb
/sdcard/bot_feed.png: 1 file pulled, 0 skipped. 31.2 MB/s (1492959 bytes in 0.046s)
/sdcard/bot_feed.png: 1 file pulled, 0 skipped. 43.4 MB/s (785747 bytes in 0.017s)
/sdcard/bot_feed.png: 1 file pulled, 0 skipped. 61.2 MB/s (1497881 bytes in 0.023s)
/sdcard/bot_feed.png: 1 file pulled, 0 skipped. 63.8 MB/s (1497183 bytes in 0.022s)
/sdcard/bot_feed.png: 1 file pulled, 0 skipped. 47.2 MB/s (1495990 bytes in 0.030s)
/sdcard/bot_feed.png: 1 file pulled, 0 skipped. 53.4 MB/s (782818 bytes in 0.014s)
/sdcard/bot_feed.png: 1 file pulled, 0 skipped. 58.9 MB/s (1490902 bytes in 0.024s)
/sdcard/bot_feed.png: 1 file pulled, 0 skipped. 60.0 MB/s (748883 bytes in 0.012s)
[I 13:35:07.114 NotebookApp] Saving file at /RR_bot.ipynb
/sdcard/bot_feed.png: 1 file pulled, 0 skipped. 49.8 MB/s (1484904 bytes in 0.028s)
[I 13:35:16.184 NotebookApp] Kernel interrupted: 9da57ad9-e136-4964-afe4-260e60edbf9d
[I 13:37:07.187 NotebookApp] Saving file at /RR_bot.ipynb

**Comment by AxelBjork** [comment]
Thanks!

The device name being given to Scrcpy is wrong, it should be handled automatically so I'm not sure why that is.

You could always just manually put device = 'emulator-5554' as it will always be that for you. You can also try seeing if just opening Scrcpy normally with the .exe works.

The port scanning code has been changed lately, so check if you have the latest version, this file,

https://github.com/AxelBjork/Rush-Royale-Bot/blob/2e4d59d1db553fe52bcf9c0f553f468811a5a81f/Src/port_scan.py

Otherwise you can try restarting ADB, either by killing the ADB in task manager or "ADB kill-server" in command line.

**Comment by AxelBjork** [comment]
Hello,

I delete the previous comment because I usually run the notebook from visual code instead of normal Jupyter notebook so not super familiar with the log you posted.

```
[I 08:12:06.242 NotebookApp] Kernel started: 59e466dc-444d-43b8-b833-84ceb2e7f550, name: python3
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: f320d224-23df-40a9-9328-4a77f9aee5bc
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached
emulator-5554   device

error: no such device '\r:5555'
error: no such device '':5555'
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
C:\Programs\Scrcpy\scrcpy-server: 1 file pushed, 0 skipped. 90.0 MB/s (41159 bytes in 0.000s)
[server] INFO: Device: OnePlus ONEPLUS A3010 (Android 7.1.1)
INFO: Renderer: direct3d
INFO: Initial texture: 896x1600
/system/bin/sh: C:ProgramsScrcpyadb: not found
Events injected: 1
## Network stats: elapsed time=12ms (0ms mobile, 0ms wifi, 12ms not connected)
/sdcard/bot_feed.png: 1 file pulled, 0 skipped. 64.5 MB/s (1499915 bytes in 0.022s)
/sdcard/bot_feed.png: 1 file pulled, 0 skipped. 63.3 MB/s (1456610 bytes in 0.022s)
/sdcard/bot_feed.png: 1 file pulled, 0 skipped. 78.1 MB/s (1523853 bytes in 0.019s)
/sdcard/bot_feed.png: 1 file pulled, 0 skipped. 67.3 MB/s (1522665 bytes in 0.022s)
/sdcard/bot_feed.png: 1 file pulled, 0 skipped. 74.5 MB/s (1496154 bytes in 0.019s)

```
This is the log I get when I launch it the same way. Basically looks like the exact same thing, so I don't think any of that is a problem. It seems to be running and pulling images from the device.

Do you get an error in the cell when you run it?

**Comment by AxelBjork** [comment]
Closed since bot should be run with GUI version now.
