### ISSUE TITLE
Few bugs/issues with the new release

### ISSUE THREAD

**Issue by T9es** [AxelBjork/Rush-Royale-Bot#15]
Hey, so I've been testing around the release with the gui. I really appreciate your work, so here's some feedback.

The scrcpy change is really good. It's finally in a point where you don't need to install and go through files, trying to set it up. Nice and simple.

As for the gui update: The gui is good, it's simple, yet it shows all the important stuff.

Now for the issues:

- The bot for some reason will NOT upgrade position 1 and position 4 with levels. For some reason it just does not work in the new gui version. 
Here's some troubleshooting for you, might make it easier and faster: Changing the config.ini manually also yields the same broken result, with no upgrades. Checking the gui on and off (these specific levels) also does not fix it.
- The new update messed up the units. The bot will try to merge ALL units with each other. Here's an example: You have a tier 1 ivy, and tier 1 wind_archer. The bot will try to merge these two together and fail. After a fail, it will go on and try to merge the next units, or repeat the action with another unit.
- DPS unit does not work. Combined with the combination issue from above, the bot will merge even the DPS units (It should not from what I've figured out before).

For all of these issues, I sadly could not go through the code and fix anything, as I've been really busy with work. Hope these points are not that hard to resolve, again, cheers for the update!

**Comment by AxelBjork** [comment]
Thanks for the feedback!

I found the problem with mana level, it just wasn't being given the user selection.

https://github.com/AxelBjork/Rush-Royale-Bot/commit/37d123b52a2dd5ab7e58d95eac10ec543084b0ed#:~:text=bot.mana_level(%5B2%2C3%2C5%5D%2Chero_power%3DTrue)

As for the dps unit, its working when I try it now. With knight_statue as dps_unit it starts merging dryads into knight_statue, just stopping the bot, changing config file and pressing start bot changes it back to demon hunter again.

The random merging sounds strange,  is the log messages also weird, or just what its doing in the game? It sounds a bit like the unit selection is not setup correctly.

The unit detection currently works great with basic units like zealot, crystalmancer, hunter, dryad, ect. however it struggles with units that change states (demon hunter, cultist) and low feature units like cauldron, knight_statue. I will look into redoing the unit detection to just using the color of the background, the current detection is also pretty CPU intensive.

**Comment by T9es** [comment]
Oh yeah, after re-downloading the bot once again, the units are fixed. It might have been some issue related to the mana, although I don't know how it would even make any connection with the recognition. As for the detection being CPU intensive, can agree. It's pulling 10-20% from my 12 thread cpu lol. Also, for the random merging log, it was as normal. No issues regarding units or any installation problems. Might have been a temporary bug. Closing this down, as the main bug is fixed, thanks again!
