### ISSUE TITLE
PVE=false in gui?

### ISSUE THREAD

**Issue by rand0mka** [AxelBjork/Rush-Royale-Bot#16]
Can you please add checkbox in GUI for pve=false? I'm collecting gold cards in PVP :-)

**Comment by AxelBjork** [comment]
Didn't realize people were using the pvp mode. I also know for anyone wanting to level a second account the pvp mode can be really useful so I added this in now.

https://github.com/AxelBjork/Rush-Royale-Bot/commit/4e51cfdd6c8516439b74519a458023b70db5e638

Let me know if it works for you!

**Comment by rand0mka** [comment]
It's good to farm gold cards in score range between 4500-5300 for my crit with this cards
sel_units= ['ivy.png','catapult.png','frost.png','monkey.png','bruser.png']

**Comment by rand0mka** [comment]
checked, thank you
