### ISSUE TITLE
✨ Add Support for the Tesla unit

### ISSUE THREAD

**Issue by Hona** [AxelBjork/Rush-Royale-Bot#22]
It will need multiple images for the charged variants.

Not sure what the numbers will do with the OpenCV detection.

I really like the bot!

**Comment by AxelBjork** [comment]
I have an updating soon ready which will change the unit detection to just look at the color of the circle/polygon of the unit so different charge variants shouldn't be needed.

I don't have Tesla so I can't add it, but if you upload a image here I can fix it. If you have robot or witch as well just throw those in a deck with Tesla.  Go on random dungeon floor and fill board with tier 1s then you can just the start bot and wait for OCR_inputs to be updated, stop the bot and upload the image(s) here. One of each unit, tier 1.

**Comment by Hona** [comment]
@AxelBjork I have extracted raw PNGs from the game of all units. I also have the overlay pngs of merge shapes.

Would these or any other game assets be of help to you?

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/10430890/183569307-7f92711a-1ceb-4781-852b-5ce5a83a0324.png">
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/10430890/183569414-e8e9a2d8-61c3-4faf-b8c3-f5da87622f52.png">

**Comment by Hona** [comment]
However, here's the output from OCR inputs:
![icon_1](https://user-images.githubusercontent.com/10430890/183570365-cf2f8581-a065-4c3e-bc36-41b48ce3095f.png)
![icon_10](https://user-images.githubusercontent.com/10430890/183570370-d4c590e7-8121-4f8d-8f39-ae3170c355fc.png)
![icon_13](https://user-images.githubusercontent.com/10430890/183570598-d7848d13-247a-45a0-9f51-f70a54446e62.png)

Let me know if you need anything more :)

**Comment by AxelBjork** [comment]
Thanks, I added them now,

https://github.com/AxelBjork/Rush-Royale-Bot/commit/a859d5e59f49f877513dde0c8de15d25e8159da3

Those game assets look interesting, really ideally the best thing would be to just be able to pull from the game's memory what unit is in each slot (and mana amount), but especially when it's running through an emulator I think it's very difficult, if not impossible.

The openCV unit detection is a bit problematic currently as doing 3x for each color in the image, 15x for each slot becomes CPU intensive. When you add on alternative states for each unit it becomes too much even with the good multithreading it's doing. Normal cauldron, knight statue also just don't have enough features compared to other units.

If you go to the `color_unit_type` branch it's matching unit just based on the most common color in the image, for a demon hunter deck I think its working better, some decks with a lot of purple I can see be problematic but you can see how it works for you with Tesla.

The rank detection is working very well, both very fast and accurate. When I checked it's about 0.05 seconds to run every slot through the logistic regression model and it's using and black/white image of the image corners with [OpenCV canny](https://docs.opencv.org/4.x/da/d22/tutorial_py_canny.html)

You can get the shape pretty well with that,

![5_input_92](https://user-images.githubusercontent.com/71280183/183573925-7018b251-9a67-409b-b1e5-aabb4cf2af66.png)![4_input_89](https://user-images.githubusercontent.com/71280183/183573985-1865e557-48c0-46b3-906a-d59eec882dfe.png)![1_input_35](https://user-images.githubusercontent.com/71280183/183574039-bdeba60a-8a54-4090-8caf-c2179b146b57.png)

I have around 700 images the model is trained on, best way to improve it in the future I think is to just add more images.
