### ISSUE TITLE
♻️ Try to keep only 2 Knight Statues (at least keep it even)

### ISSUE THREAD

**Issue by Hona** [AxelBjork/Rush-Royale-Bot#23]
Maybe 4 - or a config variable

**Comment by AxelBjork** [comment]
Added some knight statue logic to main now with this pull request,

https://github.com/AxelBjork/Rush-Royale-Bot/pull/38

Preserving the two highest knight statues should be enough.

This function will also find the grid id of a knight statue adjacent to the highest dps unit,

https://github.com/AxelBjork/Rush-Royale-Bot/blob/main/Src/bot_perception.py#L84

Unsure where to integrate, basically that slot should just be ignored but none of the merge logic is using unit position atm so have to improve structure before adding position based logic.

**Comment by Hona** [comment]
Looks great, closing!
