### ISSUE TITLE
🐛 Activated Knight Statue is often detected as Dryad

### ISSUE THREAD

**Issue by Hona** [AxelBjork/Rush-Royale-Bot#24]

**Comment by AxelBjork** [comment]
You can test the color based detection in this branch,

https://github.com/AxelBjork/Rush-Royale-Bot/tree/color_unit_type

I only started working on it 2 days ago, but it would be good to test it with some different decks before adding it to main.

**Comment by rand0mka** [comment]
test passed. Works more accurate with colors.
