### ISSUE TITLE
🐛 Several Waves go by before units are placed

### ISSUE THREAD

**Issue by Hona** [AxelBjork/Rush-Royale-Bot#28]
<img width="990" alt="image" src="https://user-images.githubusercontent.com/10430890/183779885-572bba75-b447-4355-a29f-a62cad0e8e6f.png">

**Comment by Hona** [comment]
I set my matchmaking wait to 60 - as it takes ages to find a match. Is there some way to make it check every second, but cancel after the variable?

**Comment by iOZ06** [comment]
Have you experimented with a smaller value, say between 12 and 20? I find that gives sufficient time to wait while units are still placed within the first wave.

**Comment by AxelBjork** [comment]
Hmm, I've never really had this problem as 2 seconds would still find a match most of the time.

Best thing would be to just put in a wait loop until combat started, you can look at this loop,

https://github.com/AxelBjork/Rush-Royale-Bot/blob/3bbd0defe4fe3236c1ae4263798a095a7e5a1bcf/Src/bot_core.py#L306
```
for i in range(10):
                avail_buttons = self.get_current_icons(available=True)
                # Look for correct chapter
                if (avail_buttons == 'fighting.png').any(axis=None):
                      break
```

**Comment by AxelBjork** [comment]
Added this to main now,

https://github.com/AxelBjork/Rush-Royale-Bot/commit/4eb640f2813701d05996da2749949d8aa926c979

Also had to add in a 2 second wait for it not to go by too fast. Should be waiting 2-20 seconds now before trying to back out of matchmaking.
