### ISSUE TITLE
Suggestion : focus on best unit

### ISSUE THREAD

**Issue by Blackhatfrance** [AxelBjork/Rush-Royale-Bot#3]
Any suggestion : find a way to focus and preserve best unit like hunter, and merging little one

**Comment by Blackhatfrance** [comment]
Maybe do an array for merging, like keep always 1 chemist, 1 executioner

**Comment by AxelBjork** [comment]
Agreed, sometimes it merges really bad targets when it runs out of rank 1s.

I have been working on `adv_filter_keys` to filter stuff based on type and rank,

adv_filter_keys(merge_series,[ [3,4,5], ['crystal.png'] ],remove=True)

Should for example remove any rank 3,4,5 crystalmancers from the possible targets in merge series.

Biggest problem right now is just the rank predictor which is not as good as the unit type predictor. It's a lot harder to do anything good if it can't consistently tell what rank units are.

Still I have tested other bots like https://www.zorobots.com/bot-rush-royale.html and this one will outperform it, and is actually updated for dungeon floors. With my deck, (chemist, bombardier, hunter, zealot, crystalmancer) it consistently clears floor 5 and ran for over 10 hours.

**Comment by Blackhatfrance** [comment]
Thank you for your quick reply
I tried it for few days.

Unfortually, zorobot only work on Windows and can't be emulated.

**Comment by AxelBjork** [comment]
This is kind of working now,

The customization should be improved in the future, (as well as actually adding your own units in a somewhat automated way). 

However right now it's doing this,
1. Always preserve one of highest rank chemists
2. Will never merge rank 3+ Zealot or Crystalmancers
3. Filter out units which have less than 2 of the same rank
4. Merge high priority targets (bombardier, chemist)
5. Wait until only 2 empty spots in grid
6. Merge level 1s
7. When grid is full, merge anything except those covered by 1. 2. 3. 

There's some errors in rank/unit prediction that sometimes causes it to merge certain wrong units but overall it does good.
![floor_5_33](https://user-images.githubusercontent.com/71280183/172503029-dcb7c5cf-ee8e-475f-ac09-e09514834c97.png)
