### ISSUE TITLE
✨ Only have 1 Chemist

### ISSUE THREAD

**Issue by Hona** [AxelBjork/Rush-Royale-Bot#34]
![image](https://user-images.githubusercontent.com/10430890/184064631-410d4555-1431-491e-bd62-eaf15e1c6824.png)

I'd expect the highest level chemist to stay, then merge the rest away

**Comment by AxelBjork** [comment]
The chemist logic already exists, it's hard to say what's happening here without seeing the bot output

The other merging issue can be discussed in this Issue https://github.com/AxelBjork/Rush-Royale-Bot/issues/19
