### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by mcavio** [AxelBjork/Rush-Royale-Bot#4]
Pls help me, how to run ur bot on royale
Add me on discord: PAN TAXIKAR#2028

**Comment by AxelBjork** [comment]
In it's current state it the bot is not very user friendly and might be a bit difficult to get setup. I am working on making things more portable in the future.

Current I run the RR_bot.ipyn file from visual code and specify the path to [scrcpy](https://github.com/Genymobile/scrcpy) in config.ini 

You also need bluestacks installed, in bluestacks advanced settings android debug bridge should be enabled.

All python modules needed should be in requirements.txt, so you can do `pip install -r /path/to/requirements.txt`

Specify your cards in first cell of RR_bot.ipyn and run it. Scrcpy should open and you can close it once connected.

In the second cell you can specify which cards to mana level, merge_target (dps unit), and what dungeon floor to farm.

Run second cell to start the bot.

Let me know how it goes, there should be a proper setup guide and gui for the bot sometime in the future.

**Comment by AxelBjork** [comment]
Added gui, should be much easier to install now, just first run install.bat then launch_gui.bat all you need is python (added to path) and Bluestacks setup.
