### ISSUE TITLE
Please update to v16

### ISSUE THREAD

**Issue by vood-xmr2** [AxelBjork/Rush-Royale-Bot#52]
Please update to v16

**Comment by AxelBjork** [comment]
I might not be able to update it until early next week, but from what I can tell it should be just a quick fix changing the coordinates for co-op start here,

https://github.com/AxelBjork/Rush-Royale-Bot/blob/main/Src/bot_core.py#L384

**Comment by vood-xmr2** [comment]
I changed the room confirmation coordinates, but when the battle ends and re-enters the coop, the bot starts clicking on the room 11 x300 y1320 and that's it ... then after a reboot it normally enters the room and plays the battle. I don't know what is the problem? if there is a little time, please help or correct bot_core

**Comment by AxelBjork** [comment]
I updated the button coords in main, so lower floors work. I'll add new icon and support for chapter 4 next week.
