### ISSUE TITLE
bluestacks X

### ISSUE THREAD

**Issue by GhostyyyPlays** [AxelBjork/Rush-Royale-Bot#69]
Hi there , hope your doing well ... is there anyway to get this working on bluestacks x? i've been trying but it seems that ADB is giving issues , any work around ? bluestacks 5 keeps freezing up the game after one round

**Comment by Newb420** [comment]
im using bluestacks 5.10.200.1006 and working fine.

**Comment by GhostyyyPlays** [comment]
> im using bluestacks 5.10.200.1006 and working fine.

do you perhaps have the exe for that one ? i'm trying it find it

**Comment by GhostyyyPlays** [comment]
Got it working
