### ISSUE TITLE
Maybe problem with envs

### ISSUE THREAD

**Issue by rand0mka** [AxelBjork/Rush-Royale-Bot#7]
Hi Boss!
I already spent 2 days with this problem, please help me.
I understand that problem with my envs or something with my windows machine...

I have problem with this import:
from scrcpy import Client, const

but I already tried to install all plugins for VS, tried PyCharm, but can't understand how to show python to see in right directory?
Maybe you can help me with advice here or in telegram @rand0ms
Thank you in advance.

**Comment by rand0mka** [comment]
![image](https://user-images.githubusercontent.com/20513968/180884020-d0ab2015-ec6f-447e-9388-78e45c1170cf.png)

**Comment by AxelBjork** [comment]
The package you seem to be missing is py-scrcpy-client,
https://github.com/leng-yue/py-scrcpy-client

It should be installed if you navigate to the bot folder and do`pip install requirements.txt ` or do it manually with pip.

Also I did an update 2 days ago which makes it a bit easier to install by removing pytesseract, try upgrading to that version as well.

**Comment by rand0mka** [comment]
already installed :( 
![image](https://user-images.githubusercontent.com/20513968/180999461-600dd7bc-0897-40d3-9706-2c3f6a96cbae.png)

**Comment by rand0mka** [comment]
PS C:\Code\Rush-Royale-Bot> pip install -r c:\Code\Rush-Royale-Bot\requirements.txt
Requirement already satisfied: numpy==1.23.1 in c:\users\rand0\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages (from -r c:\Code\Rush-Royale-Bot\requirements.txt (line 1)) (1.23.1)
Requirement already satisfied: pandas==1.4.3 in c:\users\rand0\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages (from -r c:\Code\Rush-Royale-Bot\requirements.txt (line 2)) (1.4.3)
Requirement already satisfied: Pillow==9.2.0 in c:\users\rand0\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages (from -r c:\Code\Rush-Royale-Bot\requirements.txt (line 3)) (9.2.0)
Requirement already satisfied: scikit_learn==1.1.1 in c:\users\rand0\.pyenv\pyenv-win\versions\3.10.0\lib\site-packages (from -r c:\Code\Rush-Royale-Bot\requirements.txt (line 4)) (1.1.1)
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.7,<3.10; 0.0.3 Requires-Python >=3.7,<3.10; 0.0.4 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement scrcpy==0.0.4 (from versions: none)
ERROR: No matching distribution found for scrcpy==0.0.4

**Comment by rand0mka** [comment]
BTW
I've tried to do same on mac os
sergeyartemiev@MacBook-Pro-Sergey RR_bot % pip install -r requirements.txt
Collecting numpy==1.23.1
  Downloading numpy-1.23.1-cp310-cp310-macosx_11_0_arm64.whl (13.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 11.3 MB/s eta 0:00:00
Collecting pandas==1.4.3
  Downloading pandas-1.4.3-cp310-cp310-macosx_11_0_arm64.whl (10.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 10.7 MB/s eta 0:00:00
Collecting Pillow==9.2.0
  Downloading Pillow-9.2.0-cp310-cp310-macosx_11_0_arm64.whl (2.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 10.3 MB/s eta 0:00:00
Collecting scikit_learn==1.1.1
  Downloading scikit_learn-1.1.1-cp310-cp310-macosx_12_0_arm64.whl (7.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 7.1 MB/s eta 0:00:00
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.7,<3.10; 0.0.3 Requires-Python >=3.7,<3.10; 0.0.4 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement scrcpy==0.0.4 (from versions: none)
ERROR: No matching distribution found for scrcpy==0.0.4

**Comment by T9es** [comment]
You are running a python version that is above 10. Install python 3.9.

**Comment by rand0mka** [comment]
Python 3.9 solved my problem with scrcpy :-), but quest still in progress

**Comment by rand0mka** [comment]
![image](https://user-images.githubusercontent.com/20513968/181093848-29391a8c-6d42-4406-84d2-37839ce84e7a.png)

**Comment by rand0mka** [comment]
![image](https://user-images.githubusercontent.com/20513968/181093963-683f4e56-da6a-45d5-8e89-bf7482e8830b.png)

**Comment by rand0mka** [comment]
![image](https://user-images.githubusercontent.com/20513968/181095313-35729500-562b-48e3-890b-b744d80ab69d.png)

**Comment by rand0mka** [comment]
Solved, thank you for this project
