### ISSUE TITLE
Curse tactic

### ISSUE THREAD

**Issue by rand0mka** [AxelBjork/Rush-Royale-Bot#9]
Hi again!
Did you think anything about tactic with cursed tile?
Maybe I can help with something?

**Comment by AxelBjork** [comment]
I looked a bit at adding this here,

https://github.com/AxelBjork/Rush-Royale-Bot/tree/Curse_dodge

However I'm not sure how well it will work.

**Comment by rand0mka** [comment]
I think better, than before, thanks
